accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login_page, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('create-an-account', views.register, name='register'),
    path('forgot-your-password', views.forgot_password, name='forgot_password'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart, name='cart')
]

covidsite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('picturegenetics.urls')),
    path('cart/', include('cart.urls')),
    path('portal/', include('portal.urls')),
    path('login/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, AbstractBaseUser
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None):
        if not email:
            raise ValueError("email is required")
        if not first_name:
            raise ValueError("first name is required")
        if not last_name:
            raise ValueError("last name is required")

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=60, unique=True)
    first_name = models.CharField(verbose_name='First name', max_length=200)
    last_name = models.CharField(verbose_name='Last name', max_length=200)

    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='date joined')
    last_login = models.DateTimeField(verbose_name='Last login', auto_now=True)

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    object = UserManager()

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def __str__(self):
        return self.email

# class AccountInfo(models.Model):
#     SexType = models.TextChoices('SexType', 'Male Female')
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     genetic_sex = models.CharField(blank=True, choices=SexType.choices, max_length=10)
#     date_of_birth = models.DateField(default=timezone.now)
#     phone = models.IntegerField(default=200)
#     address = models.CharField(max_length=500, default="332, kusa Jisalo")
#     city = models.CharField(max_length=200, default="Apo-resettlement")
#     state = models.CharField(max_length=200, default="Abuja")
#     postal_code = models.IntegerField(default=20000)
#     country = models.CharField(max_length=200, default="Nigeria")
#     language = models.CharField(max_length=200, default="English, US")

accounts/forms.py
from django import forms
from django.forms import ModelForm, TextInput, EmailInput, PasswordInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import User


class RegistrationUserForm(UserCreationForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(
        attrs={
            'class': 'login-input',
            'style': 'max-width: 350px',
        }
    ))
    password2 = forms.CharField(label='password', widget=forms.PasswordInput(
        attrs={
            'class': 'login-input',
            'style': 'max-width: 350px',
        }
    ))

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')
        widgets = {
            'first_name': TextInput(attrs={
                'class': "login-input",
                'style': 'max-width: 300px;',

            }),
            'last_name': TextInput(attrs={
                'class': "login-input",
                'style': 'max-width: 300px;',

            }),
            'email': EmailInput(attrs={
                'class': "login-input",
                'style': 'max-width: 350px;',

            }),
            'password1': PasswordInput(attrs={
                'class': "login-input",
                'style': 'max-width: 350px;',

            }),
            'password2': PasswordInput(attrs={
                'class': "login-input",
                'style': 'max-width: 350px;',

            }),
        }


class UserLoginForm(ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput(
        attrs={
            'class': 'login-input',
            'style': 'max-width: 300px',
        }
    ))

    class Meta:
        model = User
        fields = ('email', 'password')
        widgets = {
            'email': EmailInput(attrs={
                'class': "login-input",
                'style': 'max-width: 300px;',

            }),
            'password': PasswordInput(attrs={
                'class': "login-input",

            })
        }

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']

            if not authenticate(email=email, password=password):
                raise forms.ValidationError('Invalid Credentials!')

accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages, auth
from django.contrib.auth import authenticate, login, logout

# Create your views here.
from .forms import RegistrationUserForm, UserLoginForm


def register(request):
    context = {}
    if request.POST:
        form = RegistrationUserForm(request.POST)
        if form.is_valid():
            form.save()
            # messages.success(request, 'Registration successful!')

            return redirect('accounts:login')
        context['form'] = form
    else:
        form = RegistrationUserForm()
        context['form'] = form
    return render(request, 'accounts/register.html', context)


def login_page(request):
    context = {}
    if request.POST:
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']

            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                return redirect('portal:portal')
        else:
            context['login_form'] = form

    else:
        form = UserLoginForm()
        context['login_form'] = form

    return render(request, 'accounts/login.html', context)


def logout_user(request):
    logout(request)
    return redirect('accounts:login')


def forgot_password(request):
    # form = UserCreationForm()
    # context = {"form": form}
    return render(request, 'accounts/forgotpassword.html')

accounts/templates/accounts/forgotpassword.html
{% extends 'accountsbase.html' %}


{% block body %}
<div id="login-form-box">
    <form enctype="multipart/form-data" action="" method="post" id="login-form">
        <h2 class="forgot-h2">Forgot Your Pasword?</h2>
        <p style="font-size: small;">Enter the email address for your account to reset your password.</p>

        <input type="email" class="login-input" id="forgot-email" style="margin-bottom: 15px;">

        <div class="login-form-btn-box">
            <input type="submit" value="Next" class="login-button"> 
        
        </div>
        <div class="login-form-btn-box return-btn"><a href="{% url 'accounts:login' %}">Back to Login</a></div>

    </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accountsbase.html' %}


{% block body %}

        <div id="login-form-box">
            <form enctype="multipart/form-data" action="" method="post" id="login-form">
                {% csrf_token %}
                <div class="login-input-wrap">
                    <label for="email-login" class="login-label">Email</label>
                    <span id="email-login">
<!--                        <input type="email" class="login-input" > -->
                        {{login_form.email}}
                    </span>
                
                </div>
                <div class="login-input-wrap">
                    <label for="password-login" class="login-label">Password</label>
                    <span id="password-login">
<!--                        <input type="password" class="login-input" > -->
                        {{login_form.password}}
                    </span>
                
                </div>
                {% if login_form.non_field_errors %}
                    <P>{{login_form.non_field_errors}}</P>
                {% endif %}
                <div class="login-form-btn-box">
                    <input type="submit" value="Log In" class="login-button">
                
                </div>
            </form>
            <div id="other-signin-top-badge" class="login-form-btn-box">
                OR
            </div>
            <div id="other-signin">
                <div id="google-login-box">
                    <button class="google-signin"><i></i> Continue with Google</button>
                </div>
                <div id="create-forget-option-box">
                    <span class="bottom-small"><a href="{% url 'accounts:register' %}">Create an account</a>   |   <a href="{% url 'accounts:forgot_password' %}">Forgot password?</a></span>
                </div>
            </div>
        </div>
 
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accountsbase.html' %}


{% block body %}

<div id="login-form-box">
    <form enctype="multipart/form-data" action="" method="post" id="login-form">
        {% csrf_token %}
        <div class="half-form">
            <div class="login-input-wrap" style="margin-right: 10px;">
                <label for="first-name-register" class="login-label" >First Name</label>
                <span  id="first-name-register">
                    {{form.first_name}}
                </span>


            </div>
            <div class="login-input-wrap" style="margin-left: 10px;">
                <label for="last-name-register" class="login-label">Last Name</label>
                <span  id="last-name-register">
                    {{form.last_name}}
                </span>



            </div>
        </div>
        <div class="login-input-wrap">
            <label for="email-register" class="login-label">Email</label>
            <span  id="email-register">
                {{form.email}}
            </span>

        </div>

        <div class="login-input-wrap">
            <label for="password-register" class="login-label">Password</label>
        <span  id="password-register">
                {{form.password1}}
        </span>

        </div>
        <div class="login-input-wrap">
            <label for="confirm-password-register" class="login-label">Confirm Password</label>
             <span id="confirm-password-register">
                {{form.password2}}
            </span>


        </div>
        <div>
            <div id="consent-wrap">
                <input type="checkbox" value="I consent to TS" id="terms-service-check"> <label for="terms-service-check" class="consent-box-label">I agree to the Picture Genetics <a>Terms of Service</a></label>

            </div>
            <div id="consent-wrap">
                <input type="checkbox" value="I consent to PP" id="privacy-policy-check"> <label for="privacy-policy-check" class="consent-box-label">I agree to the Picture Genetics <a>Privacy Policy</a></label>

            </div>
        </div>
        <div class="login-form-btn-box">
            <input type="submit" name="Create New Account" class="login-button">

        </div>
        {{ form.errors }}

        <div class="login-form-btn-box return-btn"><a href="{% url 'accounts:login' %}">Back to Login</a></div>
    </form>
    
</div>
{% endblock %}