accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login_page, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('create-an-account', views.register, name='register'),
    path('forgot-your-password', views.forgot_password, name='forgot_password'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart, name='cart')
]

covidsite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('picturegenetics.urls')),
    path('cart/', include('cart.urls')),
    path('portal/', include('portal.urls')),
    path('login/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

portal/urls.py
from django.urls import path

from . import views
from django.contrib.auth.decorators import login_required

app_name = 'portal'
urlpatterns = [
    path('', login_required(views.PortalView.as_view()), name='portal'),
    path('tests/', views.TestsView.as_view(), name='tests'),
    path('consults/', views.ConsultsView.as_view(), name='consults'),
    path('orderhistory/', views.OrderHistoryView.as_view(), name='history'),
    path('support/', views.SupportView.as_view(), name='support'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('settings/email/', views.EmailView.as_view(), name='email'),
    path('settings/password/', views.PasswordChangeView.as_view(), name='password')
]

portal/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class TestTypes(models.Model):
    test_name = models.CharField(max_length=100)
    test_code = models.CharField(unique=True, max_length=100)
    price = models.DecimalField(decimal_places=2, max_digits=8)

    def __str__(self):
        return self.test_name


class Counselor(models.Model):
    counselor_name = models.CharField(max_length=100)
    specialization = models.CharField(max_length=150)


class TestPurchase(models.Model):
    date_purchased = models.DateTimeField()
    test_info = models.ForeignKey(TestTypes, on_delete=models.CASCADE)
    test_status = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class GiftsPurchase(models.Model):
    test_purchase = models.ForeignKey(TestPurchase, on_delete=models.CASCADE)
    gift_code = models.CharField(max_length=100)
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class OrderHistory(models.Model):
    StatusType = models.TextChoices('StatusType', 'Delivered Pending')
    date = models.DateTimeField()
    confirmation_id = models.CharField(unique=True, max_length=100)
    test = models.ForeignKey(TestTypes, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    delivery_status = models.CharField(blank=True, choices=StatusType.choices, max_length=15)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Consult(models.Model):
    time_scheduled = models.DateTimeField()
    counselor = models.ForeignKey(Counselor, on_delete=models.CASCADE)
    test_to_be_discussed = models.ForeignKey(TestTypes, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

portal/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.conf import settings
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import TestPurchase, GiftsPurchase, Consult, OrderHistory
import datetime


def time_please():
    current_time = datetime.datetime.now()
    hour = current_time.hour

    if hour < 12:
        return 'Good morning'
    elif 12 <= hour < 18:
        return 'Good afternoon'
    else:
        return 'Good evening'


# Create your views here.


class PortalView(LoginRequiredMixin, ListView):
    login_url = 'accounts/login/'
    redirect_field_name = 'portal/portal.html'
    template_name = 'portal/portal.html'
    context_object_name = 'latest_purchases'
    model = TestPurchase

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user.email
        context['purchases'] = TestPurchase.objects.filter(user=self.request.user)
        context['time_greeting'] = time_please()

        return context


class TestsView(ListView):
    model = TestPurchase
    template_name = 'portal/tests.html'
    context_object_name = 'user_tests'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['purchases'] = TestPurchase.objects.filter(user=self.request.user)
        return context

    # def get_queryset(self):
    #
    #     self.user = get_object_or_404(TestPurchase, user=self.kwargs['user'])
    #
    #     return TestPurchase.objects.filter(user=self.user)


class ConsultsView(ListView):
    template_name = 'portal/consults.html'
    context_object_name = 'latest_purchases'

    def get_queryset(self):
        return Consult.objects.order_by('-time_scheduled')


class OrderHistoryView(ListView):
    template_name = 'portal/history.html'
    context_object_name = 'latest_purchases'

    def get_queryset(self):
        return OrderHistory.objects.all()


class SupportView(ListView):
    template_name = 'portal/support.html'
    context_object_name = 'latest_purchases'

    def get_queryset(self):
        return OrderHistory.objects.all()


class SettingsView(ListView):
    template_name = 'portal/settings.html'
    context_object_name = 'latest_purchases'

    def get_queryset(self):
        return OrderHistory.objects.all()


class EmailView(ListView):
    template_name = 'portal/email.html'
    context_object_name = 'latest_purchases'

    def get_queryset(self):
        return OrderHistory.objects.all()


class PasswordChangeView(ListView):
    template_name = 'portal/password.html'
    context_object_name = 'latest_purchases'

    def get_queryset(self):
        return OrderHistory.objects.all()

portal/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>


        <meta charset="UTF-8">
        <title>Picture Genetics | Personal & Family DNA Testing</title>
        <link rel="shortcut icon" type="image/x-icon" href="https://picturegenetics.com/assets/favicon/favicon_light/favicon.ico">
        <script src="https://kit.fontawesome.com/be19714452.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'portal/portal.css' %}">
        <link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
        <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
        <script src="{% static 'portal/portal.js' %}"></script>
    </head>
    <body>
        <div id="page-content">
            <div id="left-side">
                <div id="sidebar-container">
                    <div id="brand-logo">
                        <a href="{% url 'picturegenetics:home' %}"><img data-v-e4ce0690="" src="{% static 'portal/picturegenetics logo 2.svg' %}" class="logo-img"></a>
                        
                        <i class="fas fa-angle-right"></i>
                    </div>
                    <div id="sidebar-menu-items">
                        <ul>
                            <li class="sidebar-list-items"><i class="fa fa-home" aria-hidden="true"></i><span class="sidebar"><a href="{% url 'portal:portal' %}">Dashboard</a></span></li>
                            <li class="sidebar-list-items"><i class="fas fa-vials"></i><span class="sidebar"><a href="{% url 'portal:tests' %}">My Tests</a></span></li>
                            <li class="sidebar-list-items"><i class="far fa-clipboard"></i><span class="sidebar"><a href="{% url 'portal:consults' %}">My Consults</a></span></li>
                            <li class="sidebar-list-items"><i class="fa fa-calendar" aria-hidden="true"></i><span class="sidebar"><a href="{% url 'portal:history' %}">Order History</a></span></li>
                            <li class="sidebar-list-items"><i class="fas fa-headset"></i></i><span class="sidebar"><a href="{% url 'portal:support' %}">Support</a></span></li>
                        </ul>
                    </div>
                    <div id="sidebar-return-home-link">
                        <ul>
                            <li class="sidebar-list-items">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i><span class="sidebar"><a href="{% url 'picturegenetics:home' %}">Back to Home</a></span>
                            </li>

                        </ul>
                    </div>
                    <div id="sidebar-contact-info">
                        <ul>
                            <li class="sidebar-list-items">
                                <i class="fa fa-envelope-o" aria-hidden="true"></i><span id="home-email" class="sidebar">hello@picturegenetics.com</span>
                            </li>
                            <li class="sidebar-list-items" >
                                <i class="fa fa-phone" aria-hidden="true"></i><span class="sidebar">(626)-434-3596</span>
                            </li>
                        </ul>
                    </div>

                </div>
            </div>

            <div id="right-side">
                <div id="top-nav-container">
                    
                    <div class="icon-name-dropdown">
                        
                        <button class="icon-name-dropdown-btn">
                            <i class="fa fa-user"></i>
                            {{request.user.first_name}}
                            <i class="fa fa-caret-down"></i>
                        </button>
                        
                        <div class="dropdown-content">
                            <div id="header-dropdown-content">
                                <p style="font-size: medium; padding-bottom: 0;">{{request.user.first_name}}</p>
                                <p>{{request.user.email}}</p>
                            </div>
                            <div id="main-dropdown-content">
                                <p>Account</p>
                                <a href="{% url 'portal:settings' %}"><i class="fas fa-cog"></i>Settings</a>
                                <div style="border-top: 1px solid rgb(0 0 0 / 25%);">
                                    <a href="{% url 'accounts:logout' %}" ><i class="fas fa-sign-out-alt"></i>Logout</a>
                                </div>
                                
                            </div>
                        </div>

                    </div>

                </div>
                <div class="main-page-content">
                    {% block body %}

                    {% endblock %}
                </div>


        </div>
        </div>
    </body>
</html>

portal/templates/settingsbase.html
{% extends 'base.html' %}


{% block body %}

    <div class="non-dashboard">
        <div>
             <h1 class="heading-h1">Settings</h1>
            <p>View or edit your personal information, or change your password.</p>
        </div>
        <div id="settings-page-group">
            <div id="settings-menu">
                <button class="settings-menu-btn active-settings-btn"><a href="{% url 'portal:settings' %}">Account</a></button>
                <button class="settings-menu-btn"><a  href="{% url 'portal:email' %}">Email</a></button>
                <button class="settings-menu-btn"><a  href="{% url 'portal:password' %}">Password</a></button>
            </div>
                {% block settingsbody %}




                {% endblock %}

            
        </div>
        <script>
            // try using while loops
             var btnContainer = document.getElementById("settings-menu");
              // Get all buttons with class="btn" inside the container
              var btns = btnContainer.getElementsByClassName("settings-menu-btn");
              for (var j = 0; j < btns.length; j++) {
                btns[j].addEventListener("click", function() {
                    var current = document.getElementsByClassName("active-settings-btn");
                    current[0].className = current[0].className.replace(" active-settings-btn", "");
                    this.className += " active-settings-btn";
                 });
              }
        </script>
    </div>


{% endblock %}